- name: "Update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "Upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install apache"
  become: yes
  apt:
    name: ["apache2"]
    state: latest
    update_cache: yes

- name: Creates directory
  file:
    path: /var/www/web
    state: directory
    owner: "www-data"
    mode: '0755'

- name: Copy index test page
  template:
    src: "files/index.html"
    dest: "/var/www/web/index.html"

- name: "UFW firewall allow HTTP on port 80"
  ufw:
    rule: allow
    port: "80"
    proto: tcp